# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 04:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160727_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 29, 4, 13, 18, 440502, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
