# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-22 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170322_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='secret',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='projectlink',
            name='link',
            field=models.CharField(max_length=64),
        ),
    ]
