# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_project_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hasData',
            field=models.BooleanField(default=False),
        ),
    ]
