# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 09:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_project_hasdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_hash',
        ),
    ]
