# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-29 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170322_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='collection_autoload',
        ),
        migrations.RemoveField(
            model_name='project',
            name='state_autoload',
        ),
        migrations.AddField(
            model_name='project',
            name='num_collections',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='num_states',
            field=models.IntegerField(default=0),
        ),
    ]
