# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 09:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_project_project_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_public',
        ),
    ]
