# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-03 19:08
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils.crypto import get_random_string


def random_string(apps, schema_editor):
    Project = apps.get_model('main', 'Project')
    for project in Project.objects.all().iterator():
        project.short_link_key = get_random_string(length=6)
        project.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20170408_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='short_link_key',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.RunPython(
            random_string, reverse_code=migrations.RunPython.noop
        )
    ]
