# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20160804_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectuser',
            name='user',
        ),
        migrations.AddField(
            model_name='projectuser',
            name='email',
            field=models.CharField(default=b'', max_length=250),
        ),
    ]
