# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20160804_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='view_key',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
    ]
