# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-06 03:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_project_view_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamuser',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamuser', to='main.Project'),
        ),
    ]
